### ISSUE TITLE
对应的微信版本是多少？

### ISSUE THREAD

**Issue by lkmvip** [susnmos/WXHook#1]
6.5.4无效果

**Comment by susnmos** [comment]
就是针对6.5.4写的，你是自己编译安装的吗？试试看我的deb安装有没有效果

**Comment by wxdjs** [comment]
微信6.5.4，6sp ，ios10.2 
可以转发到朋友圈，但是有个问题，转发后点击发送后，那个转发的视频留在微信界面不动，然后微信死掉了，要关闭后台才行，重新打开后发现转发成功

**Comment by susnmos** [comment]
这个问题，一开始在我手机上不存在，后来出现了该问题，不过已经修复了。等新功能完成后会提交的😊

**Comment by wxdjs** [comment]
版本号能不能跟bigboss统一下，下载了0.0.2，显示0.0-2，比bigboss还小，老提示更新

**Comment by wxdjs** [comment]
发现bug
当转发时，在微信转发界面
不管开启还是关闭默认屏蔽消息来源者，都无法选择别的转发选择，如公开，私密，部分可见，
只能是默认选中的不给谁看

**Comment by susnmos** [comment]
已经在v0.0.3中修正了这个无法选中其他屏蔽模式的问题
