### ISSUE TITLE
0.06版的bug

### ISSUE THREAD

**Issue by lkmvip** [susnmos/WXHook#4]
按钮会错位 ，比如在聊天窗口想点转发，但是实际点到的是删除

**Comment by Wee-W** [comment]
对的(¬ω¬)微信654上出现这个问题，别的版本不清楚

**Comment by susnmos** [comment]
确实，凌晨写的😢，等下发版本更新

susnm

2017年2月8日 +0800 PM12:22 Wee-W <notifications@github.com>，写道：

**Comment by susnmos** [comment]
v0.0.7 has been solved this bug.
