### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Wee-W** [susnmos/WXHook#5]
偶尔造成微信闪退，浏览信息的时候也会闪退！6SP  933  微信654！  之前的0.0.6没有这个问题！0.0.3也没有发现闪退！

**Comment by susnmos** [comment]
是在什么特殊操作之后才出现闪退的吗？从0.0.6到0.0.7只修正了一个参数而已

**Comment by Wee-W** [comment]
有时候打开微信收消息完成后闪退。有时候浏览信息闪退。有时候选择朋友圈钱包设置等等这类选项时闪退。没有涉及到插件本身的功能。我现在安装回003没有问题，微信一切正常，没有保存006的安装包。

**Comment by susnmos** [comment]
可以在bigboss源上安装（可以降级到各个版本）

**Comment by Wee-W** [comment]
跟设置中的两个开关关闭或打开没有关系....这个都试了

**Comment by Wee-W** [comment]
是在大老板源安的呀。我去看看

**Comment by susnmos** [comment]
给我发个邮件看看log

**Comment by Wee-W** [comment]
刚安好007，你说的日志是系统那个诊断日志？

**Comment by susnmos** [comment]
系统日志

**Comment by Wee-W** [comment]
我卸载了003，安装了007，到现在还没闪退。我给你邮件截图了，你看下是图片里的日志吗？

**Comment by susnmos** [comment]
帮我测测新功能？😊😄

susnm
