### ISSUE TITLE
007版闪退问题

### ISSUE THREAD

**Issue by Wee-W** [susnmos/WXHook#6]
你好，我貌似已经找到问题了。从微信通讯录选一个联系人，点发送信息，出来聊天窗口。在聊天窗口点输入栏，点语音，点联系人信息，都会闪退。卸载插件以后，就没事了。

**Comment by Wee-W** [comment]
忘记说了，6S及6SP  系统933

**Comment by susnmos** [comment]
0.0.6也有这个问题吗？是否还安装了其他的微信插件？我只有6，貌似没有发现这个问题？可否用gif或者视频模拟一下这个现象😊

susnm

2017年2月10日 +0800 AM10:07 Wee-W <notifications@github.com>，写道：

**Comment by Wee-W** [comment]
我在bigboss上找不到006的安装包。能否发我邮箱一个。我去安一个003看下先。视频模拟这个没有问题。一会给你邮箱发。

**Comment by susnmos** [comment]
好的，其他版本的话，Github上的release页面都有

susnm

2017年2月10日 +0800 AM11:40 Wee-W <notifications@github.com>，写道：

**Comment by Wee-W** [comment]
已经给你发邮件了。请查收

**Comment by susnmos** [comment]
v0.0.9已修复该问题
