### ISSUE TITLE
新增的朋友圈转发和导出聊天记录不会用，能教一下吗？

### ISSUE THREAD

**Issue by lkmvip** [susnmos/WXHook#8]
新增的朋友圈转发和导出聊天记录不会用，能教一下吗？

**Comment by susnmos** [comment]
1. 抱歉，新增的朋友圈转发，刚写完，昨天上传的部分代码是屏蔽了该功能的。稍后我会发布该版本
2. 并不是导出所有的聊天记录，只是会导出群内的照片和视频（你可以在手机内存不足的时候快速导出所有的群内已下载的照片和视频到一个文件夹下，然后使用电脑快速的导出，方便保存）。
3. 使用：我 == 设置 == 通用 == 存储空间 == 稍等一会会出现清理微信的按钮 == 然后选好需要导出的群 == 看到该群右边会有一个 i 字样的按钮，点击进入详情 == 然后你会看到右下角有操作按钮 == 你可以根据需要选中部分照片视频导出，或者选择全部导出

susnm

**Comment by lkmvip** [comment]
谢谢

**Comment by susnmos** [comment]
1. 你可以在下面看到导出的进度？最好在导出的时候不要退出该界面（导出还是很快的，我200Mb没多久就导出了）。
2. 该功能只会导出照片和视频，并不会删除该内容，你可以在此选择 操作 按钮，选择删除
3. 还有一个bug（是微信自身的bug），在没次进入 清理微信 后 小视频都会暂时无法播放。你可以重启一下桌面（SpringBoard）后再次尝试。如果有时间，我会尝试解决该bug，但是并不一定能成功。毕竟没有源代码😁

susnm

**Comment by lkmvip** [comment]
这个导出，我几乎用不到，而且我发现微信也能导出聊天室图片视频，直接在聊天室档案里面就能导出了

**Comment by lkmvip** [comment]
还是朋友圈转发吸引人，哈哈哈

**Comment by susnmos** [comment]
微信是导出到哪里啊？

不管怎么样，如果你想直接保存到电脑，肯定还是我的方便快捷。

这个功能其实一开始不在我的进度里面，只是那次显示我的手机内存不足，看到微信有好几个G的内容，才想到了这个功能。主要还是写来给自己用的。放上来方便大家使用。

了解一下：
 你使用过其它的微信转发朋友圈的插件吗？
  1. 他们在图片还没有下载的时候，能不能直接转发？
  2. 能不能转发小视频
  3. 屏蔽他人的功能应该是没写的吧

susnm

**Comment by lkmvip** [comment]
微信导出是在“查看聊天室文件”里面，右上角选择下面就有按钮导出了，不过是导出到相册里面

1，没下载不能转发
2，能转发小视频
3，没有

**Comment by lkmvip** [comment]
http://www.hsdcw.com/photo/upload/2016-4-19/2016419938362013.jpg


差不多就是这样的一个按钮

**Comment by susnmos** [comment]
已经写了、还自己画了一个转发按钮，可以转发没有下载的图（比下载的稍微模糊一点，小视频还没写

susnm

2017年2月17日 +0800 PM10:04 lkmvip <notifications@github.com>，写道：

**Comment by lkmvip** [comment]
能自动下载原图就好了，记得以前有个转发是能自动下载原图再转发的，只不过没法在新版微信使用了

**Comment by susnmos** [comment]
只是暂时的解决方案，我会再看看

susnm

2017年2月17日 +0800 PM10:08 lkmvip <notifications@github.com>，写道：

**Comment by lkmvip** [comment]
加油

**Comment by lkmvip** [comment]
兄弟有新版本了吗？

**Comment by susnmos** [comment]
刚写完朋友圈

susnm

2017年2月19日 +0800 PM3:37 lkmvip <notifications@github.com>，写道：

**Comment by susnmos** [comment]
本来想先发的，但是之前有人提了个bug，你有3d touch吗

susnm

2017年2月19日 +0800 PM3:37 lkmvip <notifications@github.com>，写道：

**Comment by lkmvip** [comment]
我没3D touch。。。。

**Comment by susnmos** [comment]
好的，等下发你新版本你用用看

susnm

2017年2月19日 +0800 PM3:41 lkmvip <notifications@github.com>，写道：

**Comment by lkmvip** [comment]
好的

**Comment by susnmos** [comment]
朋友圈转发，图片图片视频没有下载的话，会先进行下载（图片每张下载时长上限为5s，视频15s）。

susnm

**Comment by lkmvip** [comment]
ok，哪里下载？

**Comment by susnmos** [comment]
自动的，如果你转发的内容有图片或视频没有下载，插件会先下载，你会看到转发按钮变成 下载中 字样，并会在下载完成后显示转发界面。

susnm

2017年2月19日 +0800 PM4:10 lkmvip <notifications@github.com>，写道：

**Comment by lkmvip** [comment]
不是，我的意思是，插件在哪里下载？

**Comment by susnmos** [comment]
第一条邮件的附件不是吗

susnm

2017年2月19日 +0800 PM4:15 lkmvip <notifications@github.com>，写道：

**Comment by lkmvip** [comment]
邮件里面没有附件。。

**Comment by susnmos** [comment]
debs/0.1.8

**Comment by lkmvip** [comment]
ok

**Comment by lkmvip** [comment]
朋友有一种连接，就是公众号分享到朋友圈的那种，没法点转发

**Comment by lkmvip** [comment]
另外红包收益在哪个地方看？

**Comment by susnmos** [comment]
我屏蔽了这个转发，有需要吗？直接转发那个链接？
红包的话，你随便找个发过的红包，进去然后点击 查看我的红包记录，选年份的地方可以找到今天的选项

susnm

**Comment by lkmvip** [comment]
有需要，这样转发连接也方便点，请加上谢谢

**Comment by lkmvip** [comment]
还有一个，点开某个人的朋友圈，就没有转发按钮了，就是只能在自己的朋友圈转发，不能去别人的朋友圈里面转发

**Comment by susnmos** [comment]
已经在0.1.9种实现了
